### PR TITLE
Feature/count down

### PR DESCRIPTION
**Pull request by m4rtint**
Branched from https://github.com/gotty2019/GOTTY/pull/48

### CODE REVIEW

**Comment by DJSteins** [comment]
I see a lot of changes in this PR that are also in the enum player PR. Is this going to cause a merge conflict?

**Comment by m4rtint** [comment]
@DJSteins 
It shouldn't, I branched from enum branch.

**Comment by DJSteins** [comment]
@m4rtint 
Tight

**Comment by m4rtint** [comment]
[CountDown on start of game](https://trello.com/c/ucZ1N225/107-countdown-on-start-of-game)

**Pull request merged**
